name: engineering-quantum-interactions
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyterlab
  - matplotlib=3.10
  - numpy=2.1
  - pandas=2.2
  - qutip=5.2
  - scipy=1.15
  - pip
  - pip:
      - scienceplots==2.1.1

